### ISSUE TITLE
onfocusin, onfocusout can be called before module has been init()-ed

### ISSUE THREAD

**Issue by priyajeet** [box/t3js#100]
It is common practice to initialize scope variables or services within the init() of a module or behavior and then use that variable throughout the scope. If such variable is being used inside one of the onX methods, like onfocusout, onfocusin, onmessage, then there is a probability of a typeerror if those event handler methods get called before init().

example: http://jsfiddle.net/Darth/8tkz1r4t/

The optimal solution would be that if those even handlers are called before a module and its behaviors have been init()-ed, then that handling should be delayed till the init() is finished. This may require some kind of event queuing and promisifying till init is finished.

Another not-so-optimal solution is to only bind events that can be manually triggered after init() has been called. So .focus() and .blur() calls will not execute onfocusin or onfocusout till init() is done.

Alternatively, one can ignore this, and require developers from adding null checks in all those methods or check if the module is not initialized by maintaining some state in their modules (though thats hard to span across behavior inits().

**Comment by nzakas** [comment]
So to summarize, you're saying that it's possible for an `on*` method to be called prior to the completion of `init()` being called? So if the first line in `init()` calls `blur()`, then `onfocusout()` is called before `init()` finishes?

**Comment by priyajeet** [comment]
Yup

**Comment by nzakas** [comment]
I think the solution needs to match people's expectations. For instance, have we trained people to believe that `init()` will complete before any event handlers will be called? My hunch is yes, just not entirely sure. In that case, it would be unexpected to queue up events and replay them, just as unexpected as having the event handlers called before `init()` completes.

We definitely don't want to special-case events, as that will severely complicate the code. I wonder if the simplest thing would be to just not attach any event handlers until after `init()` is called? @j3tan
