### ISSUE TITLE
Attaching behaviors (with the same name) to modules more than one times

### ISSUE THREAD

**Issue by pytkin** [box/t3js#101]
Yes, sometimes this happens:
```js
behaviors: ['recording-broadcast', 'recording-broadcast'],
```
Maybe this code should throw excerption in debug mode?

**Comment by nzakas** [comment]
Yeah, that seems like a good suggestion. @j3tan thoughts?

**Comment by j3tan** [comment]
Sounds good! @pytkin, if you are interested in doing a pull request, that would be most helpful.
