### ISSUE TITLE
Application Lifecycle Events

### ISSUE THREAD

**Issue by jonathanamartin** [box/t3js#106]
We're writing some services that will be used by other developers.  Today for the developers to use our service they need to do something like the following:

```javascript
Box.Application.init()
    .getService('our-service').init();
```
Is there an easy way to make our services 'self-registering'?  In the future, we may come out with additional services and it'd be nice for our end-user not to have to update their code to use them.

If there's not a way today to do this what would you think about application lifecycle events?  We could either listen for a pre-determined message or implement a predetermined method in our services.

**Comment by j3tan** [comment]
Could you clarify what type of lifecycle events you are interested in?

We currently fire events for application 'init', 'message', and 'error'. You can listen to these by doing Box.Application.on('init', function() { ... });

**Comment by jonathanamartin** [comment]
Hi, yes, this is exactly the type of events I was looking for.  We'll be fine to use the 'init' event.  Much appreciated!
