### ISSUE TITLE
Can a behavior notify its module when it is done being initialized?

### ISSUE THREAD

**Issue by adrilo** [box/t3js#107]
Currently the module is first initialized then its behaviors are. I have a use case where the module needs to know when the behavior is done being initialized to finish its own initialization.  

To be more specific, the module starts init, then the behavior's role is to register some tutorials based on the module's config. Then I want the module to immediately start one tutorial (and it will start only if it was previously registered).

So it goes module::init > behavior::init > module::postInit?

How can this be achieved? Broadcasting a message seems the only option now but it is gross...

**Comment by j3tan** [comment]
A module should not be tied at all to its behaviors (and vice versa). You can do one of the following:
1. Broadcast a 'tutorialsready' message with a module id from the behavior/receive it on the module
2. setTimeout() from the module init() - easiest solution but implicitly couples some of the logic. Consider this if it is not a common use case.
3. Not have a behavior, and integrate logic into the module.

If the behavior is super simple, you may want to consider #3.  If the behavior exists purely for sharing code, you'll have to weigh the amount of re-use with the amount of extra code to handle behavior/module interaction (approaches #1 and #2).

**Comment by nzakas** [comment]
I think it's worth questioning if the initialization order is correct. Does it make sense for a module's behaviors to be initialized after the module's `init()` method? Perhaps not. This might just have been a legacy implementation detail that we didn't fully think through.

**Comment by j3tan** [comment]
Behaviors should work independently from the module anyway so I do not see any issues with initializing behaviors first. We could easily run into the case where the opposite happens though, like the module init() or some other behavior init() sets up something specific that another behavior relies on.

i.e. Module init() adds data-attribute to moduleEl based, behavior init() looks for that data-attribute.

I guess the question is which one has more use cases and makes more sense? Altering behavior initialization is another breaking change, so we'll have to be careful.

**Comment by nzakas** [comment]
I think the real question is this: what's the expectation about when `init()` is called? Is the expectation that all of its dependencies are loaded? If yes, then that's a good argument for initializing behaviors first so that they are all ready when `init()` is called.

**Comment by adrilo** [comment]
Ordering is indeed tricky and may or may not be what developers want, so I don't think changing the order will solve the problem entirely.
What about a `postInit()` callback in the module? That way the order would not be a problem anymore and seems like a pretty standard lifecycle event.

**Comment by nzakas** [comment]
I disagree. Adding `postInit()` introduces a strange relationship. Why is there a `postInit()`? Why wouldn't that just be the last statement in `init()` rather than another method? I think adding this would be more confusing that useful.

On the other hand, switching so that behaviors are initialized prior to the module's `init()` being called seems like it completely solves your problem and would be more in line with expectations (services must be present by the time `init()` executes, so why not behaviors?).

**Comment by j3tan** [comment]
I think it should be safe to have behaviors init() first. It is still a breaking change but it'll be grouped with the other breaking changes we have, including post-init module event binding, coming up in 2.0.
