### ISSUE TITLE
Box.JQueryDOM is using a global $ namespace

### ISSUE THREAD

**Issue by trunghung** [box/t3js#108]
Would it possible for Box.JQueryDOM to use jQuery's window.$ as an injected dependency rather than using it directly as a global variable?  My project has some conflict with the $ namespace due to legacy code so we use jQuery.noConflict to remove the window.$ variable.  Is it possible to change Box.JQueryDOM to save its instance of jquery and use it internally so that when the window.$ variable goes away, Box.JQueryDOM isn't broken. thanks

**Comment by j3tan** [comment]
We will look into injecting 'jQuery' as a dependency for our -jquery bundles.
