### ISSUE TITLE
Services and modules inheritance.

### ISSUE THREAD

**Issue by maxmironov** [box/t3js#109]
Hi guys, I wonder, if T3 supports any kind of services and/or modules inheritance?

For instance, I have `message-list-service` that renders messages list with its author nicknames. Now I want to create `messages-list-service-with-photos`, which additionally renders author's avatar. Is there a way to reuse `message-list-service` code or the aggregation and modification of generated DOM is the only way?

**Comment by nzakas** [comment]
Modules are specifically not allowed to inherit from one another, however, you can use behaviors to have reusable code between modules.

**Comment by maxmironov** [comment]
Thank you for feedback.
