### ISSUE TITLE
T3 Test bundle doesn't stub out fire or on method

### ISSUE THREAD

**Issue by trunghung** [box/t3js#110]
Currently the application object passed into a service doesn't have these methods stubbed out, is there any plan to add support for these methods?  My services fire and listen to events, so I would need these stubs to proper unit test them. thanks

**Comment by j3tan** [comment]
If you wish, you can manually add the on/off functions
```
var application = new Box.TestServiceProvider({...});
application.on = function() {};
application.off = function() {};
```
and stub it out as normal. 

If you want to use the actual EventTarget, just do:
```
var application = new Box.TestServiceProvider({ ... });
$.extend(application, new Box.EventTarget());
```

**Comment by trunghung** [comment]
I am doing that right now by mixing the EventTarget with the methods returned by Box test bundle.  It would be nice for the test bundle to stub on the core functionalities of the framework.

**Comment by j3tan** [comment]
We've traditionally made this an explicit step to make sure our TestServiceProvider just doesn't become another Application object with built in logic. I'll take a look around to see if this is something we will consider adding.

Thanks for the feeback!

**Comment by j3tan** [comment]
We won't be adding this at this time. Please continue mixing in EventTarget
