### ISSUE TITLE
Best Way to Stop a User From Navigating Away

### ISSUE THREAD

**Issue by jonathanamartin** [box/t3js#111]
I'd like to prompt users before they navigate away from a page if a certain condition is met.

What would you recommend?  I was thinking I could capture all page clicks with some sort of master module that wraps the whole page.  Then use a service to read and update the state which would indicate whether or not a user could proceed.

There's probably a more elegant solution. Any thoughts would be greatly appreciated.

Thanks,
Jonathan

**Comment by j3tan** [comment]
I don't have enough context here to help you make a decision. Why capture all of the page clicks? You can just put something in the onBeforePageUnload event handler that can check the page state and prompt the user before they leave. If you are checking state across multiple modules, I would make this a singleton service that each of the modules will register against in their init() with a callback like isSafeToExit() or something. The isSafeToExit() will simply check the module's state to see if its able to leave the page without prompting. The service will just call all of these callbacks when the page is about to exit.

**Comment by jonathanamartin** [comment]
These are great suggestions.  I'll think I'll give the singleton service with registered callbacks a shot.  We can't do the unload event because it's a SPA with no page unload.

Thanks for the quick feedback.
