### ISSUE TITLE
Add pre-registered services whitelist to TestServiceProvider

### ISSUE THREAD

**Issue by j3tan** [box/t3js#113]
Due to the way we use Karma, we include all of our behaviors, services, and modules on one single page. This leads to some poor unit tests since the real services are automatically included when they should have been mocked out in the test. No warning is given to the developer that this is actually happening.

To fix this, we need to add the ability to specify a list of services we expect to have access to from the `TestServiceProvider`. For example,
```
Box.TestServiceProvider = function(serviceStubs) {
     this.stubs = serviceStubs || {};
};
```
might become

```
Box.TestServiceProvider = function(serviceStubs, allowedServices) {
     this.stubs = serviceStubs || {};
     this.allowedServices = allowedServices || [];
};
```

then `getService()` will validate that the service is in the allowedServices before fetching a pre-registered service. An example usage might be:

```
var context = new Box.TestServiceProvider({
   foo: { bar: ... }
}, ['dom', 'promises']);
```

**Comment by j3tan** [comment]
@nzakas - Thoughts?

**Comment by nzakas** [comment]
LGTM
