### ISSUE TITLE
Question: why jQuery dependency?

### ISSUE THREAD

**Issue by bitinn** [box/t3js#12]
I understand Box.com might be using jQuery features extensively, but if T3's idea is to stay modular, then why not decouple jQuery as well.

Looking at the documents (apologize if I missed something), it seems jQuery would be used for data-binding, but there can be lots of approach to data-binding, not to mention virtual-dom approach (where binding is handled differently)

Seems like T3 can be done without jQuery, or at least with alternatives like [DOMtastic](https://github.com/webpro/DOMtastic).

Either way, I am just very excited to see a *framework* that takes progressive enhancement into account and I am very interested in using it for my current project.

**Comment by nzakas** [comment]
Thanks, we actually do cover this in our README:
https://github.com/box/t3js#why-is-there-a-dependency-on-jquery

It's basically for event normalization across browsers.

**Comment by bitinn** [comment]
missed it :)

If that's the case though, there must be something that can cover your need without loading jQuery into it right? How about this:

https://github.com/desandro/eventie

**Comment by bitinn** [comment]
Also note that `DOMtastic` mentioned above use the same api as jQuery, and you can build event system independent of other components.

Is it possible to allow developers to substitute jQuery? Just a suggestion.

**Comment by nzakas** [comment]
If you want to use a library that has the same event interface as jQuery (`$().on`), then you can use it already. There are literally only two references to jQuery in T3:

https://github.com/box/t3js/blob/master/lib/application.js#L378
https://github.com/box/t3js/blob/master/lib/application.js#L431

So if you can make those methods work with another library, there's nothing stopping you from doing so right now.

**Comment by bitinn** [comment]
Ah, many thx for your answers.

**Comment by appsforartists** [comment]
If that's the case, you should abstract this so:

a) People who don't need IE8 don't need to add a dependency or shim an API,
b) People who do can explicitly plug in a microlibrary like [Gator](https://github.com/ccampbell/gator) to solve the dependency, and
c) Future versions don't accidentally presume jQuery.

    T3.EventAPI = userProvidedAPI || $;

    function listenTo (target, eventType, listener) {
      if (T3.EventAPI) {
        T3.EventAPI(target).on(eventType, listener);

      } else if (target.addEventListener) {
        target.addEventListener(eventType, listener);

      } else {
        throw new Error("T3 requires an event library like Gator or jQuery for IE8 support");
      }
    }

**Comment by bitinn** [comment]
+1 to @appsforartists, though I don't know the exact reason why polyfill can't be used in this case, since IE8 appear to be the source of problem.

**Comment by nzakas** [comment]
We are looking at removing jQuery once we can EOL IE8. We were looking at further extracting the jQuery-ness before open sourcing and just ran out of time. If you're interested, please file a separate issue suggesting building such an abstraction and we'll see if we either get some time or can find someone to contribute.

**Comment by nzakas** [comment]
We've opened https://github.com/box/t3js/issues/22 to continue discussion about how to abstract out event handling.
