### ISSUE TITLE
Testing lib could have more methods available

### ISSUE THREAD

**Issue by yconoclast** [box/t3js#123]
I need to spy on some functions from T3 and it would be really cool to have those available on the testing lib.

* init
* destroy
* start
* stop

**Comment by nzakas** [comment]
When you say "testing lib", what do you mean?

**Comment by yconoclast** [comment]
Sorry here [https://github.com/box/t3js/blob/master/dist/t3-testing.js](https://github.com/box/t3js/blob/master/dist/t3-testing.js#L398)

Is it possible to have some more methods?

**Comment by nzakas** [comment]
You're talking about having those on `Box.Application `?

**Comment by yconoclast** [comment]
yes exactly, at this moment I have to include a new file defining those methods to be able to test it, do you think it could be a nice thing to include?

**Comment by nzakas** [comment]
Potentially. What would you expect them to do?

@j3tan?

**Comment by j3tan** [comment]
Almost always you will be using the `TestServiceProvider` in your tests and not the application-stub. That said, in services, it is perfectly reasonable to make calls to `start()`/`stop()`, but I'm not sure about `init()`/`destroy()`. Is there a little more background on what you are testing? I would probably just extend the `TestServiceProvider` manually in my test setup

```
var application = new Box.TestServiceProvider({ ... stubs ... });
application.start = function() {};
application.stop = function() {};

var service = Box.Application.getServiceForTest('some-service', application);
```

**Comment by yconoclast** [comment]
yeah at this moment I'm only using start and stop, I have a service that starts and stops modules.

And I'm including this in order to be able to spyOn on these functions

```javascript
Box.Application.start = function () {};
Box.Application.stop = function () {};
```

I'm totally comfortable in overriding them locally in my project, but I thought that maybe someone else may need them.

I don't really need to test if the module as started or not because I totally trust this framework :)

**Comment by j3tan** [comment]
Sounds good! I think we'll defer on adding this for now. Thanks for the suggestion though
