### ISSUE TITLE
Question: possible to make T3 work with commonjs libraries?

### ISSUE THREAD

**Issue by bitinn** [box/t3js#13]
Since T3 has it's own dependency management, eg. `getGlobal`, it will probably make using it with commonjs-based libraries a bit difficult.

Do you have any recommended approaches? Can we still `browserify` or `webpack` using T3 somehow?

**Comment by nzakas** [comment]
Can you explain more about what you're trying to do?

Keep in mind, you can still use `require()` inside of T3 code if you want to. `getGlobal()` and `getService()` are there for environments that don't have `require()`.

**Comment by bitinn** [comment]
Oh good, so module loading with `getGlobal` is optional.

I was wondering if T3 encourage a specific app structure, like you should only load with `getGlobal` and write adapters for third-party libraries.

Say I am using [virtual-dom](https://github.com/Matt-Esch/virtual-dom), what I can do is:

A. use `browserify` to create a standalone dist.js of it, and import its exported global into T3.
B. use `require('virtual-dom')` in our T3 code, and let `browserify` manage the build and dependencies.

Both can be considered modular, for T3, is A the encouraged approach?

**Comment by nzakas** [comment]
Just to be clear: `getGlobal()` and `getService()` are *not* module loaders. They are just methods to access previously-loaded modules. 

Yup, A is the way we'd recommend doing that.

**Comment by bitinn** [comment]
Got it, `require()` in my context isn't a loader neither, as I was referring to a `browserify` build (a bundled file).

If A is the preferred approach then my only issue would be whether it's worth it to have 2 separate dependency management tool: one is my T3-based app, the other is `browserify`.

In order to work with npm package like `virtual-dom`, usually we need to require a few other modules as well, so we would have 1 browserify build, and then we would load them into a T3-based app.

**Comment by nzakas** [comment]
I'm sorry, I don't have experience building such an application, but I'm happy to provide guidance if you're going to give this a try. We'd love to hear about the experience.

**Comment by MrNice** [comment]
(From a cursory perusal of T3's style and architecture)
T3 makes the assumption that you're starting from first principles, from just what browsers give you. It does not expect anyone to be familiar with the various developments and trends on JavaScript application design, including production deployment practices such as using a packer like Requirejs, browserify, webpack to "build" a minified version of the source.

T3 is happy to consume such a resource as a module, so long as the framework's implementation does not drastically overreach. It may be difficult to construct an angular-based app with t3, with each module having its own ng-app attribute (or something similar).

One of the keys to T3 is that modules have a lifecycle divorced from the webpage's, and so there are assumptions that a generic browserified bundle will make about the lifecycle that will be wrong.

Browserify can probably consume T3 as well, but there's a chance is would require modifying the [compiler pipeline](https://github.com/substack/browserify-handbook#compiler-pipeline).

**Comment by nzakas** [comment]
Fixed by #40. Will work with our next release.
