### ISSUE TITLE
Need a Yeoman generator?

### ISSUE THREAD

**Issue by hwclass** [box/t3js#135]
Hi there,

Do you think that T3 needs a Yeoman generator to generate some modules, services and behaviors?

Looking for some interesting ideas,

Thanks,

Barış Güler

**Comment by nzakas** [comment]
I think a Yeoman generator would be a great addition to the ecosystem. We have one internally but it's really specific to how our app is setup. Are you interested in creating a general purpose T3 Yeoman generator?

**Comment by hwclass** [comment]
Yes, I am interested in to create a yeoman generator. I am also planning to create a sample T3 demo working with React components. So it would be useful to create a generator to use the library with other middlewares included easily as well.

**Comment by hwclass** [comment]
Ok, then. Can you conduct for where to start? For example, if we think that we can create a Yo generator, it is needed to suggest on an ideal project structure for that creation process. For example, if I generate a service by typing in terminal as "yo t3js", where do you think that is the best place for creating the services (by typing "yo t3js:service dummyService") for example? I think that the project structure is basically can be structured or can be parametrized by yeoman console.

**Comment by hwclass** [comment]
Or maybe we can start by creating a new directory in this repository as "generator-t3js"... Looking for the comments and ideas as well ;) Thanks for your patience :)

**Comment by nzakas** [comment]
I think you want to ask where JavaScript files belong, and then create `services`, `modules`, and `behaviors` as subdirectories under that directory.

**Comment by zephraph** [comment]
Here's my perspective:

`yo t3`: Generate out specified modules, services, and behaviors in subdirectories at the desired location.
`yo t3:[module|service|behavior]`: Generate a the specified item in the desired directory (defaulting to the current working directory).

**Comment by hwclass** [comment]
The latest proposal is fine I think. 

"yo t3" : The creation for the project structure
"yo t3 : [module|service|behavior] name" : The creation for the specified addition (exm: yo t3 : module textEditor)

Do you all think that fit the needs? Then I can make a pull request the first step for yeoman generator of the framework...

Thanks.

**Comment by zephraph** [comment]
At the very least I think that's a good starting point. @nzakas should the generator be in its own repo?

**Comment by nzakas** [comment]
@zephraph yes. We are happy to provide guidance but can't manage the generator at this time.

**Comment by zephraph** [comment]
:+1:

**Comment by zephraph** [comment]
@hwclass I feel like we should close this issue. If you create a repo for the generator feel free to link it back here.

**Comment by nzakas** [comment]
Good idea @zephraph
