### ISSUE TITLE
T3 in ES2015 or ES2016?

### ISSUE THREAD

**Issue by hwclass** [box/t3js#136]
And it is possible to convert the library's code into es2015 or es7 syntax.

What do you think about it?

Thanks,

Barış Güler

**Comment by zephraph** [comment]
I'm actually opposed to this. Current transpilers tend to add a bit of weight to the final output. That's fine for a large project where maintenance gains you get from transpiling out weight the cost of the extra javascript output. The appeal to this library is that it's simple. You don't _need_ ES2015+ for this project. 

Plus, this project is very stable. Touching a lot of code to essentially get a little bit cleaner syntax opens up the potential for bugs without actually gaining anything substantial. As a consumer of a library you shouldn't concern yourself with what its written in as much as how well it works and how large it is. 

With all that being said you can absolutely use this library with ES2015 today. There's no inherent need for the library to run off of ES2015 to be able to use it effectively with ES2015.

**Comment by nzakas** [comment]
You can still use T3 as it is with ES6-7 without changing over the source code. (Changing over the source code has little benefit but introduces a lot of work and risk.)

Here's an example of how to use T3 with ES6 modules:

```js
import * as T3 from "./t3";

T3.Application.addModule("foo", function() ());

T3.Application.init();
```

**Comment by hwclass** [comment]
Yes, got it. Is it thought to change the code structure of the sample todo app into ES6 / ES7 to be a reference for the new-comers into T3.js world?

**Comment by nzakas** [comment]
I don't think that's a good idea right now. ES6 is still very new and fully implemented everywhere, so most people are familiar with ES5 only. For right now, I think it's best to keep the examples in ES5.
