### ISSUE TITLE
DOMEventDelegate t.hasAttribute is not a function error

### ISSUE THREAD

**Issue by buzzfeedjoe** [box/t3js#140]
When assigning event handlers with `DOMEventDelegate`, it bubbles up through all parent nodes until it gets to the `document` object (`document.body.parentNode.parentNode`) and then this line errors because `hasAttribute()` is not defined for that object:

https://github.com/box/t3js/blob/master/dist/t3-jquery-2.0.2.js#L251

This is the error message in the console:

`Uncaught TypeError: t.hasAttribute is not a function`*`

**Comment by j3tan** [comment]
Thanks for posting. I will likely address this by checking if element.nodeType === 1

**Comment by zephraph** [comment]
@j3tan are you planning to address this soon?

Would just

```javascript
return element && element.hasAttribute && element.hasAttribute('data-type');
```

be sufficient?
