### ISSUE TITLE
Start multiple modules on Box.Application.start

### ISSUE THREAD

**Issue by hwclass** [box/t3js#141]
Hi all,

The library has methods like .start, startAll, .stop and stopAll. This can be a good idea to add specific control over making only some modules start or stop. For example,

If developer expects to see only two modules to start to work, this could be like the following:

Starting the specific modules :

```javascript
App.start(['testModule1', 'testModule1']);
```

or 

```javascript
App.startOnly(['testModule1', 'testModule1']).
```

What do you think?

Thanks.

**Comment by j3tan** [comment]
Adding some more flexibility to the `Application.start()` method sounds like a good idea, but we'll want to maintain the interface of Element, not module names. We would also like to avoid adding an additional "start" method to avoid confusing new developers.

Would this still solve your needs?

```
var moduleEls = document.querySelectorAll('[data-module="foo"], [data-module="bar"]');
Application.start(moduleEls);
```

**Comment by zephraph** [comment]
I'd also recommend just creating a service for this. 

```
Box.Application.getService('module-initializer').start('testModule1', 'testModule2');
```

My original thought was just loop through the arguments and run application.start. @j3tan does that given snippet work with the current version of t3?

**Comment by j3tan** [comment]
No, it does not work with the current version, but is a proposed change. Iterating over the `arguments` object works nicely if you hard code the modules you want to start. If you are dynamically putting together a list of modules to start, an array is better suited.

A service like @zephraph suggested could accomplish the task without modifying the Application code.

**Comment by hwclass** [comment]
In addition, I was planning to implement an array keeping the module names like the following:

if(arguments.length > 1) {
   //make a loop for the array of the module names and their modules
} else {
   //here is the actual code of stop method
}

You can take a look here: [https://gist.github.com/hwclass/cac01eb8a87636b3c317](the new stop method for multiple module call)

**Comment by j3tan** [comment]
Array.isArray(arguments) is always false since arguments isn't an Array.

Keep in mind, there can be multiple modules on a page with the same module name. Building and iterating over array mappings can be cumbersome.

For now, you could just do:
```
function start(elements) {
    var moduleEls = Array.isArray(elements) ? elements : [elements];
    for (var i = 0, len = moduleEls.length; i < len; i++) {
        Box.Application.start(moduleEls[i]);
    }
}
```

**Comment by zephraph** [comment]
Have we concluded that this can be accomplish via a service an isn't required to be an addition to T3? If so, this issue and #142 should likely be closed.

**Comment by j3tan** [comment]
Closing for now, we will try to keep the interface as straight forward as possible.
