### ISSUE TITLE
Stop multiple modules on Box.Application.stop

### ISSUE THREAD

**Issue by hwclass** [box/t3js#142]
Developer can try stopping multiple modules on stop method:

Stopping the specific modules :

```javascript
App.stop(['testModule1', 'testModule1']);
```

or

```javascript
App.stopOnly(['testModule1', 'testModule1'])
```
What do you think?

Thanks.

**Comment by j3tan** [comment]
Closing for now, we will try to keep the interface as straight forward as possible.
