### ISSUE TITLE
Allow module configuration object to be available ahead of module creation

### ISSUE THREAD

**Issue by j3tan** [box/t3js#143]
Use Case:

I have two mutually exclusive behaviors that need to be added to the module depending on the context.

```
Box.Application.addModule('foo', function(context) {
    var behaviors = ['bar'];

    if (context.getConfig('enableFeature')) {
        behaviors.push('new-behavior');
    } else {
        behaviors.push('old-behavior');
    }

   return {
        behaviors: behaviors
   };

});
```

Currently, the Context object method, `getConfig()`, can only read module config after the module instance is created. It is built that way because it caches the configurations after reading (https://github.com/box/t3js/blob/master/lib/application.js#L612). While this is more optimal, it makes configuring dynamic behaviors difficult.

@nzakas - Thoughts?

**Comment by j3tan** [comment]
Note: Dynamic behaviors would make static analysis difficult.

**Comment by zephraph** [comment]
Oh, wow, I thought this could already be accomplished. 

Definite :+1: from me. 

You're absolutely correct in that it could make static analysis difficult, but I have a similar requirement. In my use case there is a code base that is shared among different stakeholders. We work within a CMS system and there are (or will be) a set of modules that everyone shares. It was intended to use this very technique in order for each stakeholder to be able to add custom behaviors to their module based on the needs of their brand.

**Comment by nzakas** [comment]
Makes sense. The config is just metadata, so there's no reason it shouldn't be accessible immediately.
