### ISSUE TITLE
Allow the registration of custom event types

### ISSUE THREAD

**Issue by zephraph** [box/t3js#146]
Currently the event types that are accessible via `on<event>` are hard coded as an array in the `DomEventDelegate`. Would it be viable to allow the registration of custom events so that the use of `on<event>` could be expanded beyond that hard coded array?

It goes without saying that the events would have to be registered prior to the initialization of the module attempting to use said events. There's also the fact that only events that bubble would work, so it might be best to pass in the actual event object and ensure that bubbling is `true` for that event. 

Thoughts?

**Comment by j3tan** [comment]
This will be good, especially with the advent of the newer events that some browsers are supporting. We'll still provide a base set of events but will allow you to initialize T3 with an override list of events.

```
Application.init({
    eventTypes: ['click', ...],
    ...
}
```
As you mentioned, this would allow developers to trip themselves up if they forget about bubbling.

**Comment by zephraph** [comment]
I think for this model to be successful there would need to be a way to sanity check that an event is actually can be bubbled up. I think that's the hard problem to figure out here.

**Comment by nzakas** [comment]
You can't really tell if an event can bubble until after it happens, or unless you create a whitelist, which is why T3 has that. What we could do is allow any event name to be registered, but if the `event.bubbles` property is `false`, throw an error. Hopefully that would let people catch it during development.

**Comment by zephraph** [comment]
:+1: I think that's a great solution.

**Comment by zephraph** [comment]
I'll try to get to this in the next few days.

**Comment by j3tan** [comment]
I'll handle this one @zephraph
