### ISSUE TITLE
Get a build without the commonJS/AMD compatibility layer

### ISSUE THREAD

**Issue by zephraph** [box/t3js#148]
I'm in the process of transitioning from a requireJS driven system to one that is a complete bundle with only T3. We weren't actually using requireJS to pull any async dependencies so it's not really needed. 

During this transitional phase we're including both our old requireJS code and our new, slimmed down T3 code. Unfortunately if we deliver the T3 code _after_ our legacy code base then it detects that require is defined and doesn't act how we'd like. 

Ultimately having an alternative version of `wrap-end.partial` without the compatibility layer would be ideal. Could we perhaps add hooks to the build process to optionally strip out compatibility layer? Not necessarily as something that's done as part of the normal release process, but something available such that we could manually trigger the build after we pull down T3 from npm and get a version without the commonjs/amd compatibility.

**Comment by j3tan** [comment]
I'm afraid that might make the build system more complicated than it already is. You may want to add this into your own build scripts though as I don't think this specific case is something a library should handle. I'm not too familiar with AMD but I'm hoping you can just wrap the T3 dist file with another closure:

(function() {
   var define = null;

  // Contents of t3.js

}());

**Comment by zephraph** [comment]
Ahh, hey, that's a good idea. 

Thanks.
