### ISSUE TITLE
emit to a single module instead of broadcasting

### ISSUE THREAD

**Issue by Tsur** [box/t3js#149]
Hi guys,

this is just a question issue about having different instances of the same module and trying to emit an event to an specific instance instead of broadcasting it to all running instances. A way to do it could be achieved by matching the `module` and the event data in the `context.broadcast` method with an identifier so it would be possible to ensure than a broadcast is actually sent to an specific instance but not to all of then (which makes it not to actually be a "broadcast"), but it adds extra work. Let me give you an example. 

```html
<div data-module="foo" data-id="1" />
<div data-module="foo" data-id="2" />
<div data-module="bar" />
```

```js
Application.addModule('foo', function(context) {
   
    const MODULE_ID = context.getElement().dataset.id;

    return {
        messages: ["helloFoo"],
        onmessage: (name, data) => {
          
            if(!data.id || data.id === MODULE_ID) console.log(data.text);

        },
        init: function() {
            console.log('foo');
        }
    };
});
```

```js
Application.addModule('bar', function(context) {
    return {
        init: function() {
           
           // Send to just foo module with id 1
            context.broadcast('helloFoo', {text:'helloFoo', id: "1"});

          // Send to just foo module with id 2
            context.broadcast('helloFoo', {text:'helloFoo', id: "2"});

         // Send to all foo modules
            context.broadcast('helloFoo', {text:'helloFoo'});
        }
    };
});
```

other possible way could be this ...

```js
Application.addModule('foo', function(context) {
   
    const MODULE_ID = context.getElement().dataset.id;

    return {
        messages: ["helloFoo.1", "helloFoo.2"],
        onmessage: (name, data) => {
          
           let [name, id] = name.split('.');

            if(!id || id === MODULE_ID) console.log(data.text);

        },
        init: function() {
            console.log('foo');
        }
    };
});
```

```js
Application.addModule('bar', function(context) {
    return {
        init: function() {
           
           // Send to just foo module with id 1
            context.broadcast('helloFoo.1', {text:'helloFoo'});

          // Send to just foo module with id 2
            context.broadcast('helloFoo.2', {text:'helloFoo'});

         // Send to all foo modules
            context.broadcast('helloFoo', {text:'helloFoo'});
        }
    };
});
```

Sorry guys if I'm missing some basic stuff here, but there's a way to do it  without having to worry about ids, some emit method instead of a broadcast, how do you guys manage this stuff ? or is this approach totally wrong and should it be managed by stopping and starting modules ?

Thanks so much

**Comment by nzakas** [comment]
Messages are specifically designed to *not* target a single module, so the reason you're having trouble is because this isn't the way the system is designed to work. What you're doing is akin to a remote procedure call that tightly couples the two modules together, and T3 is designed to avoid such tight coupling. If you need that level of direct interaction, you probably want to combine the modules into a single module to keep it self-contained.

**Comment by Tsur** [comment]
Hi @nzakas, thank you for the answer, but do you mean then that modules are designed to be instantiated just once, as a singleton ?  I'm facing the problem of having a module lets call it `info` that I want to reuse, and then another module `save` with a save button than will trigger the entity info validation, but I do not want that from triggering validations on all modules. 

```html
<div class="tab">
    <div data-module="info">
       <div content-editable>Entity Name</div>
    </div>
    <div data-module="save">
       <button>Save Entity</button>
    </div>
</div>

<div  class="tab">
    <div data-module="info">
       <div content-editable>Entity Name</div>
    </div>
    <div data-module="save">
       <button>Save Entity</button>
    </div>
</div>
```

So now, when clicking on `Save Entity` that shall broadcast a `validate` message which are going to be received by the entity module, validating it and in case it is right, broadcast another message `save` received by `save` module which will save it. This is, as you can figure out, not right as the message will be received by all `entity` and `save` modules, so lets combine those modules into one simply named as  `entity`and manage this by events API instead of message API.

```html
<div class="tab" data-module="entity">
    <div>
       <div content-editable>Entity Name</div>
    </div>
    <div>
       <button>Save Entity</button>
    </div>
</div>

<div class="tab" data-module="entity">
    <div>
       <div content-editable>Entity Name</div>
    </div>
    <div>
       <button>Save Entity</button>
    </div>
</div>
```

But then if in the future, I do need to extend some of those entity modules(see below), I'll be duplicating logic in `entity` module and `another_entity` module as both, for instance, need to handle logic for the save button. So here is where behaviours come handy to share that same logic? and message API should be only used to let modules know about something has going on in the system to let them take some action if required. is it right ? sorry if all of this sounds too crappy and thanks again.

```html
<div class="tab" data-module="entity">
    <div>
       <div content-editable>Entity Name</div>
    </div>
    <div>
       <button>Save Entity</button>
    </div>
</div>

<div class="tab" data-module="another_entity">
    <div>
       <div content-editable>Entity Name</div>
    </div>
   <div>
       .... whatever
    </div>
    <div>
       <button>Save Entity</button>
    </div>
</div>
```

**Comment by j3tan** [comment]
Not sure about your usecase, but you could built an API/SDK service that handles save. Then you wouldn't actually broadcast any messages and just use the service directly from whatever module verified your form.
```
if (verified) {
  api.save(formData);
}
```

**Comment by Tsur** [comment]
yep, sure, `save` is managed by a service, but point is where do you call this method from, I do not want to duplicate that service method calls, I guess that behaviours is a good way to put this stuff.

thanks so much for you help!
