### ISSUE TITLE
Test API Documentation

### ISSUE THREAD

**Issue by zephraph** [box/t3js#151]
T3 has great API documentation with the exception of the Test API. Can we possibly create a Test API section within the documentation?

**Comment by j3tan** [comment]
There are several pages in the Guides that show you how to use the Test API

http://t3js.org/docs/guides/testing-bundle

We can add a section to our API documentation for the testing utilities.

**Comment by zephraph** [comment]
The API section is what I was referring to specifically. That would be incredibly useful.

**Comment by j3tan** [comment]
Written and pushed.
