### ISSUE TITLE
context.getConfig usage documented incorrectly, missing functionality

### ISSUE THREAD

**Issue by zephraph** [box/t3js#154]
Context.getConfig is documented a bit incorrectly. Here's the part I'm talking about:

<img width="733" alt="screen shot 2016-02-29 at 8 18 55 pm" src="https://cloud.githubusercontent.com/assets/3087225/13414558/bc2fdd94-df21-11e5-9444-d4a73430fbe7.png">

It seems to imply from an api level that you can actually pass in an element which is not the case. That also spawns a question. Should there a way to get the config of another module without referencing Box.Application directly or writing a service to do so?

**Comment by j3tan** [comment]
I'll fix the documentation. The short answer is no, a module should not be aware of another module so it doesn't make sense to grab configs for it.

**Comment by zephraph** [comment]
Yep, after some thought I completely agree.

**Comment by zephraph** [comment]
Fixed by #157.
