### ISSUE TITLE
Add new onmessage pattern to documentation

### ISSUE THREAD

**Issue by j3tan** [box/t3js#160]
We will need to document the new onmessage pattern:

```
onmessage: {
  somemessagename: this.handleSomeMessage
}
```

**Comment by j3tan** [comment]
I would also verify/document that "this" for handleSomeMessage is the module/behavior instance.

**Comment by zephraph** [comment]
We probably should've done that before merging. Would you like me to add a new unit test to verify that?

**Comment by zephraph** [comment]
@j3tan you might want to take a look at #161 as soon as possible. I think we might've broken things for people with 2.2.0. You were right, the message context wasn't the module/behavior instance and we missed that.

**Comment by j3tan** [comment]
Yeah, @nzakas's original comment on the `bind()` was to use `call(this,...)`

I briefly thought that instance.onmessage[name](name, data); would cover it, but since we're indexing into the object key, we lose that context.

**Comment by zephraph** [comment]
Well, it's fixed now. Thanks for the quick response! I'll try to tackle the documentation portion of it tonight.

**Comment by j3tan** [comment]
I've added basic documentation for this to the T3 docs
