### ISSUE TITLE
Box.Context and Box.TestServiceProvider have incorrect constructor properties set to Object

### ISSUE THREAD

**Issue by aplatti** [box/t3js#172]
Hi T3! 

I'm running into an issue in my project that is caused by subtle problem with the way that Box.Context and Box.TestServiceProvider are defined.  The methods on those objects are set by completely replacing  the prototype properties with a new object, which causes the constructor property to become Object, instead of the correct Box constructor functions.

The current code defines the methods on these object like this:

```
	function Context(application, element) {
		this.application = application;
		this.element = element;
	}

	Context.prototype = {
		broadcast: function(name, data) {...},
		getService: function(serviceName) {...},
		...
	}	
```

Because the prototype is replaced by `{}`, the constructor becomes object.

The fix is simple:

```
	function Context(application, element) {
		this.application = application;
		this.element = element;
	}

	Context.prototype.broadcast: function(name, data) {...};
	Context.prototype.getService: function(serviceName) {...};
	...
```

I'm happy to create a PR, but just wanted to run it by you guys first for feedback.  

Thanks!
Adam

**Comment by j3tan** [comment]
Hi Adam,

I think the changes you proposed are perfectly fine and a PR would be most helpful!

**Comment by nzakas** [comment]
You can also restore the constructor, for a smaller change: 


```js

    function Context(application, element) {
        this.application = application;
        this.element = element;
    }

    Context.prototype = {
        constructor: Context,
        broadcast: function(name, data) {...},
        getService: function(serviceName) {...},
        ...
    }   
```

**Comment by aplatti** [comment]
Hi guys, I made a pull request here:
https://github.com/box/t3js/pull/173

Thanks!
