### ISSUE TITLE
Preventing click events for disabled elements

### ISSUE THREAD

**Issue by aplatti** [box/t3js#174]
Hi guys,

One issue that's come up on the projects I've done with T3 is that buttons, etc. with "disabled=true" attributes still trigger "onclick" events for modules and behaviors.   I'm curious whether you think it would be appropriate for the T3 click handler to absorb these clicks, so that the modules do not receive them.   Otherwise the module has to check for the disabled attribute itself, which in my experience, is not expected by the developers, and slightly bloats the code with redundant checking for "disabled" attributes.

I'm happy to submit a PR that checks for a "disabled" attribute on a clicked element before forwarding the  event to the module or behaviors.

Thanks!
Adam

**Comment by j3tan** [comment]
No, T3 should not handle this natively. There have been many times where we wanted a tooltip to trigger, even for a disabled button.

**Comment by j3tan** [comment]
Also, 'onclick' is not special cased at all and all events are handled in the same way. We would want to avoid adding any special casing for specific event types.

**Comment by aplatti** [comment]
Gotha, makes sense. Thanks for the feedback. :)
