### ISSUE TITLE
Question on module dynamic configuration

### ISSUE THREAD

**Issue by T0RAT0RA** [box/t3js#177]
Hi,

I'm building a dialog service that creates a modal dialog (using bootstrap) then load the content by ajax.
The loaded content contains a module, so I use `Box.Application.startAll()` to start it.

Here is a sample of the code to open a model:
```
var dialogService = Box.Application.getService('dialog');
dialogService.modal().open('/scheduling/shift/edit')
```

On the dialog service I have somehting like this:
(I've simplify the code since it is not final yet)
```
return {

     modal: function() {
         this.dialog = createModal('#modal-template');
         return this;
     },

     open: function(url) {
         var self = this;

         return ajax.get(url).then(function(content) {
             self.dialog.body = content;
             Box.Application.startAll(self.dialog.$el);
         });
     },
 ```

My problem is, when I open the dialog, sometimes I need to pass some parameters to the module that will be loaded in the modal.
I understand that the module should not be aware of where it's call, so I came up with the idea of changing the configuration dynamically, before starting the module.

I would do something like this on the dialog service:
```
open: function(url, config) {
         var self = this;

         return ajax.get(url).then(function(content) {
             self.dialog.body = content;

            if (config) {
                //Extend the current module configuration with the config passed by the service
                var existingConfig = Box.Application.getModuleConfig(self.dialog.$el),
                    newConfig = object = $.extend({}, existingConfig, config);

                //Then replace the tag "script[type="text/x-config"]" with the new config
            }

             //The module should now have the extended configuration
             Box.Application.startAll(self.dialog.$el);
         });
     }
```

It feels hacky but I couldn't find another to solve this problem. do you have better ideas?

Thanks for your help!

**Comment by j3tan** [comment]
I personally would send the additional configurations in the AJAX call and append it to the content, server-side.

**Comment by T0RAT0RA** [comment]
Ok, thanks for the tip!
