### ISSUE TITLE
broadcast callMessageHandler method is fired before module is init

### ISSUE THREAD

**Issue by guumo** [box/t3js#179]
When the behaviour is initialized, if fire broadcast message, the module call onmessage method before init method.

```js
        Box.Application.addBehavior("myBehaviour", function(context) {

            return {
                init: function() {
                    context.broadcast("customMessage", {});
                }
            };

        });

        Box.Application.addModule("myModule", function(context) {

            var internalVar;

            return {
                behaviors: ["myBehaviour"],
                messages: ["customMessage"],
                onmessage: function(name, data) {
                    console.log("internalVar: " + internalVar);
                },
                init: function() {
                    internalVar = "internalValue";
                    console.log("internalVar: " + internalVar);
                }
            };

        });

        Box.Application.init();
```

Output:

```
internalVar: undefined
internalVar: internalValue

```

**Comment by zephraph** [comment]
I would say that this is the expected behavior. Each behavior of a module is initialized before the module itself. 

What are you trying to achieve that's creating this situation?

**Comment by guumo** [comment]
It is logical that the behavior starts before, but when a behavior sends a message , you should ensure that the modules have previously invoked its init method. If a module needs to perform some action that is a prerequisite for listening to a message , it will fail because it has not been invoked the init method.

**Comment by j3tan** [comment]
The easiest way to get around this is just wrap it in a set timeout. Your initialize methods probably shouldn't broadcast messages immediately as it could block the rest of your app from initializing and subscribing to the event.
