### ISSUE TITLE
Which is the best way, to have same module multiple times in an html page.

### ISSUE THREAD

**Issue by paschalidi** [box/t3js#180]
I started working with T3js framework in order to keep my code structured and easy scalable.
Loved the ideas that the creators had and the simplicity behind them.

I want to find out the right way to include the same module twice (or more times) in the same page without the **ids** and the **data-modules** to get messed up.

Take a look at the T3js documentation and examples and specifically at the TODOS example (http://t3js.org/examples/todo/). What I want to do is something like that -> http://prntscr.com/c30r0y, but at the same time make sure that the ids are not messed up, and the instantiations of the module are independent.

**Comment by j3tan** [comment]
All you need to do is have data-module="module-name" on the element. You do not need to specify an id as that will be auto-populated for you with a unique name

**Comment by paschalidi** [comment]
Could you please explain this with an example ?

**some-module.js**

```
Box.Application.addModule('some-module', function(context) {
    'use strict';
    var moduleEl,
        moduleId;

    
    return {
        init: function () {
            moduleEl = context.getElement();
            moduleId = moduleEl.getAttribute('id');
            $("button").click(function () {
                console.log('Only one module has been clicked! ')
            });
            //I know that I shouldn't use jq here but its a stupid example :) 
        }
    }
});
```

**some-html.html**

    <div data-module="helloworld">
        <button data-type="a-btn">Love T3JS</button>
    </div>
    <div data-module="helloworld">
        <button data-type="a-btn">Love T3JS</button>
    </div>
    <div data-module="helloworld">
        <button data-type="a-btn">Love T3JS</button>
    </div>
    <div data-module="helloworld">
        <button data-type="a-btn">Love T3JS</button>
    </div>

So as you said every module has a different Id which is perfect, but how can I seperate the button inside this module ? 
One way for sure is using  context.getConfig() but is that the right way or there is something even better that I could do in this case ?

**Comment by j3tan** [comment]
Yep, each module is self contained and handles the DOM inside of itself.
