### ISSUE TITLE
Service ID, not Module ID, when creating new services.

### ISSUE THREAD

**Issue by noahdecoco** [box/t3js#182]
On this page: http://t3js.org/docs/getting-started/service, the second line in the second paragraph, I think it's meant to be: "This method accepts two arguments: the **_service_** ID and a creator function." It's just a tiny typo. :)

I absolutely love the structure, robustness yet minimalism of T3. I've been trying to use this architecture since I watched a talk by Nicholas Zakas a few months ago. Thanks for the great work!

**Comment by j3tan** [comment]
thanks for the catch!

**Comment by j3tan** [comment]
Fixed!

**Comment by noahdecoco** [comment]
Cheers! :D
