### ISSUE TITLE
rename box to t3

### ISSUE THREAD

**Issue by allyraza** [box/t3js#183]
Hi there,

I have been using very similar boilerplate for past couple years now, t3 has some really nice features and event handling is much better I must say, I see you guys have a default namespace Box is it possible to rename it T3 so I don't have to change and recompile every time.

Thank you

**Comment by zephraph** [comment]
The requested change would be a breaking change and would require a major release. While I can understand where you come from (we also change the box namespace), I don't know that it's worth the breaking change. 

Just my 2 cents.

**Comment by j3tan** [comment]
Yes, we will not be changing the namespace to T3, sorry! We use the Box namespace heavily (such as `DOMEventDelegate`) and there isn't enough value in changing it.

I recommend just having a separate JS file that contains `var T3 = Box;`
