### ISSUE TITLE
Question re: setting up private variables

### ISSUE THREAD

**Issue by domchristie** [box/t3js#184]
First of all, l Iove the philosophy and design of this framework :)

Is there a difference between setting a private variable in a module's `init` method vs. setting it in the creator function? e.g.

```js
Box.Application.addModule('post', function (context) {
  var config
  var channelName

  return {
    init: function () {
      config = context.getConfig()
      channelName = config.channelName
    }
  }
})
```

vs.

```js
Box.Application.addModule('post', function (context) {
  var config = context.getConfig()
  var channelName = config.channelName
})
```

The reason I ask is that I have a module that needs to listen out for dynamic message names that it derives from the module's config:

```js
Box.Application.addModule('post', function (context) {
  var config = context.getConfig()
  var channelName = config.channelName
  var pusherService = context.getService('pusher')
  pusherService.setupChannel(channelName)

  return {
    messages: [channelName + ':' + 'new-comment']
  }
})
```

(`pusherService` creates a Pusher channel, and converts Pusher events to T3 broadcasts)

This seems to work, but in the [T3 documentation](http://t3js.org/docs/guides/modules#retrieving-the-module-element), the code example shows declaring the `element` variable in the creator function, but setting it in `init`. For dynamic message names, this wouldn't work, as `channelName` would be `undefined`.

So my question is, is there any harm in setting up private variables in the creator function this this way?

Thanks

**Comment by j3tan** [comment]
Module config is available to the module creator function so what you are doing may work. The main issue is with the lifecycle methods. For example, something like setupChannel should probably be in the init() call of the module, and removed in the destroy(). If a module hasn't been initialized, it technically shouldn't interact at all with the application (messages included) and creating a module does not necessarily mean that it has been started yet.

**Comment by domchristie** [comment]
> something like setupChannel should probably be in the init() call of the module

Yes, that makes sense (in an earlier version of that example code I did just that, but wanted to demonstrate an extreme example :)

However, in the absence of direct messaging between modules, I do seem to be scoping message names quite a lot. For example, the `post` module only wants to respond to relevant comment messages, so each broadcast message needs to be scoped with a post ID e.g. `post-42:comment-submitted`.

I wonder if there is a better way to do this? I have considered using unscoped message names and including the parent resource ID in the eveent data:

```js
context.broadcast('comment-submitted', { postId: 42 })
```

and then checking in `onmessage`:

```js
Box.Application.addModule('post', function (context) {
  var id

  return {
    init: function () {
      id = context.getConfig().id
    },
    messages: [ 'comment-submitted'],

    onmessage: {
      'comment-submitted': function (data) {
        if (data.postId === id) console.log('Comment submitted!')
      }
    }
  }
})
```

But then you have potentially lots of modules doing unnecessary checks :/

**Comment by j3tan** [comment]
correct, that's the best way. You can even annotate the post-id on the post HTML element if you don't feel like using module configuration. Then you can just do like if(data.postId === context.getElement().getAttribute('data-post-id'))

**Comment by domchristie** [comment]
Great, thanks!
