### ISSUE TITLE
getGlobal namespace

### ISSUE THREAD

**Issue by Wyzix33** [box/t3js#185]
Hi, i just started using T3 and want to use some external library, the problem is that it has a namespace like
PSI.Select
PSI.Virtual
...
i can start a new instance by 
var x = new PSI.Select(); 
x.init();  
...
so in order to import my PSI.Select to a module i tried

context.getGlobal('PSI.Select'); 

but it doesn't work
Is there a way to retrieve a reference by name using a namespace  or do i have to create a reference of PSI.Select in the global scope and name it for example 

PSISelect
and then 
context.getGlobal('PSISelect');

Thanks and great job with this wonderful framework👍

**Comment by zephraph** [comment]
Ah, `getGlobal` can only get direct objects on the global scope.

I think you're trying to do this:
```
var x = context.getGlobal('PSI').Select()
```

**Comment by Wyzix33** [comment]
Thanks, it works, i used 

var x = context.getGlobal('PSI').Select; 

I need many instances of select inside a module and i can now use 

var input1 = new x(options); 
var input2 = new x(options);  ...

Thanks
