### ISSUE TITLE
Check if a module is started from inside a module and start sub-modules

### ISSUE THREAD

**Issue by Wyzix33** [box/t3js#189]
Is it OK to check if a module is started from inside another module like this:

```
Box.Application.addModule('content', function (context) {
    return {
        messages: ['navigation'],
        onmessage: {
            navigation: function (data) {
                var e = document.getElementById(data.location);
                if(e && Box.Application.isStarted(e)) return false;  // <------------
                var  domService = context.getService('dom');
                domService.setHTML(context.getElement(), data.location);
            }
        }
    }
});
```

or should i check if it is started inside the service 'dom' like this

```
Box.Application.addService('dom', function (application) {
    return {
        setHTML: function (element, html) {
            var e = document.getElementById(html);
            if(e && application.isStarted(e)) return false;  // <------------
            application.stopAll(element);
            var g=document.createElement('div');
            g.setAttribute("data-module", html);
            g.setAttribute("id", html);
            element.appendChild(g);
            application.startAll(element);
        }
    };
});
```
This is in the event that the user click on the same menu, i don't want to restart all modules for that page again if it's already started.
And one more thing, one module will start several others, like if the menu "Home" is clicked i start the module home that will add 4 other modules inside it (a list of services, a search, a custom header if it is logged or not and a tasks module ), do i have to add and start them inside my service 'dom' or can i add and start them inside home module?
Or is it better to have another service that get's a list of modules to add and start... and any module can send it's list of needed sub-modules ..maybe...
Any thoughts? 
Thanks

**Comment by j3tan** [comment]
Services should be responsible for starting/stopping modules, not other modules. You shouldn't ever reference `Box.Application` directly from within a module.

I don't quite understand what you are trying to do with your `setHTML` function, if you just want to appending arbitrary html to some element, you should append it first then just call startAll on it.

HTML
```
<div id="container" data-module="parent-module">
     <div id="children-container"></div>
</div>
```
dom service:
```
setHTML: function(element, html) {
   application.stopAll(element);
   element.innerHTML = html;
   application.startAll(element);
}
```
parent module:
```
onmessage:
   ...
   dom.setHTML(document.querySelector('#children-container'), moduleEl);
```


Just a note that I'll be away for the holidays and will not be able to respond to any further questions for a while.

**Comment by Wyzix33** [comment]
I see, so i should be fine adding all modules as html and application.startAll(element); should start them all.

Thanks
