### ISSUE TITLE
Can click be triggered?

### ISSUE THREAD

**Issue by Wyzix33** [box/t3js#191]
Hi, i have a module with multiple tabs, can i trigger click on module init so that onclick get's executed with elementType = "tab-1"? 
If not, i can create a function and call it on init and onclick, but just wandering if it is possible, i couldn't find anything about firing events to specific module elements.
```
init: function () {
         // trigger click
},
onclick: function (event, element, elementType) {
            if (elementType === 'tab-1') {
            ...
            }
}
```
Thanks

**Comment by j3tan** [comment]
You can call this.onclick() manually as its just a normal object. I would advise against it though, possibly refactoring whatever function you wish to execute as a separate function

```
init: function() {
  this.foo();
},
onclick: function() {
    this.foo();
},
foo: function() {
   ...
}
```
