### ISSUE TITLE
Question on best practice to start/stop modules on breakpoint change

### ISSUE THREAD

**Issue by tonymihay** [box/t3js#193]
Hi there!

In my application I have several modules which should run only on "desktop" breakpoint.
In order to improve performance on "mobile" viewport I would like to get them stop after breakpoint switch. But at the same time, they should get back to work on "desktop". 
Has anyone faced the same issue?
I have an idea to create a service which will start/stop modules on breakpoint switch. But I'm not sure whether it is a good way.

**Comment by j3tan** [comment]
I'm going to close this since it's not really an issue.

However, it does sound like you're on the right track with using a service to start/stop modules.
