### ISSUE TITLE
Can services  listen for message broadcasts?

### ISSUE THREAD

**Issue by Wyzix33** [box/t3js#196]
Hi, i have a service (A) that broadcast when an element was resized using 
```
Box.Application.broadcast('resized', 'Element resized');
```
is it possible for other service (B) to listen for this message and run a function, so i don't have to add logic on every module to trigger the service (B) function?

```
onmessage: {
 resized: function(a) {
        elementResized();
      }
}
```
Thanks

**Comment by Wyzix33** [comment]
Thank you, it works great! 
Didn't see this ```message``` event in the docs... 
This is what i used:
```
   application.on('message', function(msg) {
    if (msg.data.message === 'resized') {
     doStuff(msg.data.messageData);
    }
  });
```

```msg.type``` was always a string ```message``` i thing that's the event type or something.

Thanks

**Comment by Wyzix33** [comment]
One more thing, i see that the listener is not removed once i navigate to another page, do i have to call 
```
application.off('message', function(msg) {
    if (msg.data.message === 'resized') {
     doStuff(msg.data.messageData);
    }
  });
```
inside my ```destroy()``` function? 
or how do i remove the event when i destroy the module?
Thanks

**Comment by andreyvolokitin** [comment]
This API is created for non-t3js code to be able to listen to the app events (https://github.com/box/t3js/blob/master/lib/application.js#L756), so it probably not automatically handled by t3js and you should bind/unbind it manually

**Comment by Wyzix33** [comment]
Can you give me an example how to bind/unbind a custom event? 
I don't understand i can stop a listener that was't started/added by me... 
Thanks

**Comment by andreyvolokitin** [comment]
See [Event Target API](http://t3js.org/docs/api/event-target/). The listener was added by you if you did what you described in your [comment](https://github.com/box/t3js/issues/196#issuecomment-531458381): you added an event handler function to the `message` event thrown by `t3js`. Now if you want to remove this event handler you should unbind it with `application.off('message', referenceToTheSameHandlerFunction)`

**Comment by Wyzix33** [comment]
Right... i was loosing reference to that function and it wasn't removing the event... 
It works now,

Thank you,
