### ISSUE TITLE
Change error reporter to `mocha`

### ISSUE THREAD

**Issue by bitinn** [box/t3js#20]
current reporters:

`reporters: ['progress', 'coverage', 'threshold']`

it outputs:

![screen shot 2015-04-17 at 12 48 24 am](https://cloud.githubusercontent.com/assets/1484279/7186341/81115e76-e49b-11e4-8c0c-bb995f0a3773.png)

which is fine if you don't have an error, but let's say [sandbox.verifyAndRestore](https://github.com/box/t3js/blob/master/tests/application-test.js#L28) failed, you will see this:

![screen shot 2015-04-17 at 12 52 49 am](https://cloud.githubusercontent.com/assets/1484279/7186416/1a616c06-e49c-11e4-950c-00a8390dd3ee.png)

which is difficult to debug because you don't know which test it is, your test name doesn't show up since you run `sandbox.verifyAndRestore` in the `afterEach` block (technically, the test passed, it's your `afterEach` block that failed)

since you are using `mocha`, I recommend replacing `progress` with a reporter that better support mocha, eg. https://www.npmjs.com/package/karma-mocha-reporter, which outputs:

![screen shot 2015-04-17 at 12 55 51 am](https://cloud.githubusercontent.com/assets/1484279/7186548/226812b4-e49d-11e4-8dd5-9bd2bb4687d8.png)

and when you failed:

![screen shot 2015-04-17 at 12 56 59 am](https://cloud.githubusercontent.com/assets/1484279/7186553/2868ffd4-e49d-11e4-9467-7ecdc613970d.png)

![screen shot 2015-04-17 at 1 01 24 am](https://cloud.githubusercontent.com/assets/1484279/7186572/553cdc60-e49d-11e4-9d53-276b0ac47062.png)

better?

**Comment by nzakas** [comment]
Ah interesting, it looks like your console doesn't properly support the progress reporter. What are you using?

**Comment by bitinn** [comment]
screenshot from travis and osx 10.10.3

**Comment by nzakas** [comment]
Are you using iTerm or something else?

**Comment by bitinn** [comment]
I am using Terminal, with bash profile like this, but I don't think it matters:

```
# colorful ls
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
```

Maybe you can show me the expected result? Also what do you expect Travis to print?

**Comment by bitinn** [comment]
I still believe the main issue is running `sandbox.verifyAndRestore` in the `afterEach`, it's obviously convenient, but not what mocha designed to handle (test should fail, not afterEach)

**Comment by nzakas** [comment]
Yeah, unfortunately that's the only way to catch any uncalled mocks after tests.

We will look at changing the reporter, but want to look at a few other options as well.
