### ISSUE TITLE
Demo has small issue

### ISSUE THREAD

**Issue by nsisodiya** [box/t3js#21]
Steps
=====
1) Open http://t3js.org/examples/todo/live
2) Click on Completed - url will automatically changed to http://t3js.org/examples/todo/live/completed/
3) Now type a New TODO
4) Hit Enter Key
5) You will see checkbox will be automatically selected, it should not.

**Comment by nzakas** [comment]
I can't reproduce in Chrome. What browser are you using?

**Comment by nsisodiya** [comment]
Firefox.

**Comment by priyajeet** [comment]
Yeah I see the issue, its cross browser, just that its not noticeable in chrome due to the visual coloring of the select all check box >> that todoMVC uses.
