### ISSUE TITLE
Confusion about phrasing on behaviors being accessed by modules

### ISSUE THREAD

**Issue by masak** [box/t3js#28]
In [Thinking in T3](http://t3js.org/docs/guides/thinking-in-t3), heading "Loose Coupling of Components":

> 1. Modules cannot access other modules directly.
> 2. Modules cannot access behaviors directly.
> 3. Behaviors cannot access other behaviors directly.
> 4. Behaviors cannot access modules directly.
> 5. [fifth point not relevant to this issue]

These all make sense to me &mdash; except point 2, which seems flat-out wrong.

Later, in [Understanding Behaviors](http://t3js.org/docs/guides/behaviors), heading "Using Behaviors", this code example is shown:

    Box.Application.addModule('test-module', function(context) {
    
        return {
    
            behaviors: [ 'behavior-name' ],
    
            init: function() {
                //code
            }
    
        };
    
    });

That's a module accessing a behavior directly. In fact, it seems to me that the main raison d'être of behaviors is for modules to directly access them.

Or does this not count as "directly", because we're accessing the module through its string *name*, and the framework takes care of the lookup? But this doesn't hold up, because (as far as I could find out), this *only* happens with modules accessing behaviors, but not with any of the other three combinations.

Furthermore, the "Loose Coupling" section continues: "Only services can be accessed directly by modules and behaviors". This access looks a bit different, but is essentially also a string lookup:

    var anotherService = application.getService('another-service');

So I'm confused. It seems to me that behaviors can be accessed directly by modules just as much as services can.

Am I missing something fundamental here? What is the purpose of point 2?

**Comment by nzakas** [comment]
> That's a module accessing a behavior directly. In fact, it seems to me that the main raison d'être of behaviors is for modules to directly access them.

This is a declarative reference, not direct access. Direct access would involve retrieving the behavior object and manipulating it directly. The module has no idea what methods exist on the behavior, or really, anything about it besides a name. 

> Furthermore, the "Loose Coupling" section continues: "Only services can be accessed directly by modules and behaviors". This access looks a bit different, but is essentially also a string lookup:

You'll note that in this example, the service object is returned so the module can use its methods. This is direct access.
