### ISSUE TITLE
.map file reference should not include `/dist` folder

### ISSUE THREAD

**Issue by tomByrer** [box/t3js#31]
The [`/dist` folder](https://github.com/box/t3js/blob/master/dist/t3.min.js#L18) for the `.map` file reference in your minified file will not be present once it is served via [jsDelivr CDN](http://www.jsdelivr.com/).  It will also mess up if people serve the files via their local host.

I guess add `--source-map-url` to your [uglifyjs prefs](https://github.com/box/t3js/blob/master/Makefile.js#L248), but then you'll have to add [more filenames](https://github.com/box/t3js/blob/master/Makefile.js#L227-L230).  Sorry I'd do a PR myself, but no time to test.  & I'm allergic to CLA that I'm not being payed for :P.

Let me know if you'd prefer `.map` files on jsDelivr...

**Comment by nzakas** [comment]
I'm assuming you mean this line in the minified file:

```
//# sourceMappingURL=./dist/t3.min.js.map
```

Should instead be:

```
//# sourceMappingURL=t3.min.js.map
```

**Comment by tomByrer** [comment]
Yes exactly, thank you Niicholas.

I'm assuming the '/dist' is there for the rawgit CDN.
