### ISSUE TITLE
update docs with more info around focus/blur

### ISSUE THREAD

**Issue by DavidBanksNZ** [box/t3js#32]
Hi - I have not written anything with T3 yet, but am currently reading the docs and the part about blur and focus events being unsupported surprises me. 

I think it's quite common to want extra functionality on form inputs when a user focuses or blurs them. Example: consider a sign-up form. When the username input is blurred, it can be useful to use ajax to query the server to check that the provided username is valid (and not already in use), and then to display a message alongside the input.

What would you suggest is the best way forward in this situation? I guess you could add the events manually in the module init function but that doesn't sound like a good practice. I thought about onkeyup, but that could trigger unnecessary multiple ajax requests to the server.

**Comment by priyajeet** [comment]
If you notice, the events that are supported are the ones that bubble. Blur and focus don't.

**Comment by DavidBanksNZ** [comment]
Apparently those 2 events aren't supported by Firefox though, which is a little disappointing

**Comment by priyajeet** [comment]
Well, that's where jquery event normalization helps. If you look at application.js, the events are bound using jquery, which supports those events. OR in your own code you could just try shimming it too.

**Comment by nzakas** [comment]
You could also use the change event:
https://developer.mozilla.org/en-US/docs/Web/Events/change

For purely visual changes, you can use CSS :hover as well.

**Comment by DavidBanksNZ** [comment]
Thanks for the info. Completely forgot about the change event!

Perhaps in the docs where it mentions blur and focus are unsupported, this could be expanded upon a little by some of the info provided in this thread?

**Comment by nzakas** [comment]
Good idea, we will tackle this as a documentation change.
