### ISSUE TITLE
Adding support for focus and blur

### ISSUE THREAD

**Issue by SteveALee** [box/t3js#48]
In reading through the docs i see you have the usual problem with blur and focus event's not bubbling.

These events *are* useful, especially in keyboard accessibility for drawing a clear focus indicator (though perhaps CSS support is better now). Also they are often required for keyboard access in custom controls.

We can't use the bubbling focusin focusout until Firefox supports them, see https://bugzilla.mozilla.org/show_bug.cgi?id=687787

A common approach is to use a capturing handler to get the event earlier - eg http://yuiblog.com/blog/2008/10/07/onfocus-onblur/

**Comment by nzakas** [comment]
You can use focusin and focusout everywhere thanks to jQuery. We recommend using those instead of focus and blur.

We aren't going to add support for any non-bubbling events as we don't want to start hacking in custom events flows.

**Comment by SteveALee** [comment]
OK. 
Thanks for the tip. You should update the docs to suggest this.
That gives a dependency on jQuery but I see you already have that.

I don't use jQuery much but agree it is good for browser abstraction. Is bulky so might try Zepto.

**Comment by nzakas** [comment]
Yup, we have #32 to update the docs. You should be able to use Zepto without any issues.
