### ISSUE TITLE
Create a better way to reuse modules.

### ISSUE THREAD

**Issue by pvieira91** [box/t3js#49]
It wouldn't be nice to have a better way to reuse modules? Based on the spikes that I've done with T3 and from what I've understood from the documentation, If I want to reuse a module I must import the script and also the html. Couldn't be implemented a feature where the module(script) wraps html and add it to the DOM in runtime? 

Eg. For reusing a module(Based on todo example)

From
```
<header id="header" data-module="header">
    <h1>todos</h1>
        <form data-type="new-todo-form">
            <input id="new-todo" data-type="new-todo-input">
        </form>
</header>
```

To

```
<header id="header" data-module="header">
</header>
```

**Comment by nzakas** [comment]
You can certainly implement modules that way if you prefer. However, that's outside the scope of what T3 is designed for. I'd recommend using T3 with something like React or Backbone to get this effect.
