### ISSUE TITLE
Suggestion: consider distribute this framework as bower package too

### ISSUE THREAD

**Issue by rui-infotrack** [box/t3js#53]
As per title, I think many users would love to just do `bower install t3` to install this framework, like me ; ).
Is there any plan to distribute this on bower?

Also, speaking of bower, `npm install t3` is also a common way for people (those who use browserify for example) to download this framework.

**Comment by ktei** [comment]
By the way, the author is above is me (used a company account by mistake).

**Comment by nzakas** [comment]
You can already do `npm install t3js` (see http://t3js.org/docs/getting-started/installation).

We skipped bower packaging as it seems like the trend is towards using npm for client packages (especially since the jQuery plugin registry closed).

Will npm install work for your use case?

**Comment by ktei** [comment]
Yeah, fair enough. Personally I forked this project and added it as a submodule. What I was thinking is that there are projects which are heavily dependent on bower so giving those users a bower package would be easier for them to maintain. But as you said the trend is going towards npm.

**Comment by nzakas** [comment]
Cool, closing for now. I'd prefer to wait until someone tells us they can't use T3 without Bower support before we go through the process of adding Bower. We're switching to using just npm for this and it's refreshing. :)
