### ISSUE TITLE
Add docs for dynamic loading of modules

### ISSUE THREAD

**Issue by devel-pa** [box/t3js#54]
Hi, I like your approach but I don't find something in your documentation: 

How to load modules without having an index.html with all of them. 

Something independent of the main page and encapsulated in a single container.

Thanks

**Comment by chchrist** [comment]
I don't think it is possible by design.

From the docs:

> T3 assumes that the HTML content is already present and simply allows components to interact with that content. We believe that progressive enhancement is a more robust approach for large-scale applications.

**Comment by nzakas** [comment]
It is possible to load a new module after initial page load. You'd need to retrieve the HTML, insert it, make sure the module JS is downloaded, then call `Box.Application.start()` on the element that represents the module. We will add some documentation around this.

**Comment by devel-pa** [comment]
Thanks for your answers. 
Not quite my type of thinking for large & dynamic interface applications. 
To explain myself: I don't want an index.html of 350K. Is very hard to manage and drives on too many issues.

**Comment by nzakas** [comment]
No problem, this approach is different from a lot of others, and it may not be for everyone. I'm going to keep this issue open until we add the documentation I mentioned.
