### ISSUE TITLE
Register t3js package in bower.

### ISSUE THREAD

**Issue by miguel-perez** [box/t3js#56]
Hi there,

I'm currently working on a rails app that uses [rails-assets](https://rails-assets.org/) to manage 3rd party libraries, like this one. It's using bower, and all it needs is a copy of the current manifest.json file with "bower.json" as the file name. 

http://bower.io/docs/creating-packages/

Thanks.

**Comment by nzakas** [comment]
Is it possible for you to use npm instead? We've been asking people to use that so we don't need to manage two different ways of packaging.

**Comment by miguel-perez** [comment]
I'm looking into installing https://github.com/gaslight/npm_assets in the project, that might do the trick.

**Comment by nzakas** [comment]
Cool, let us know how it goes.

**Comment by miguel-perez** [comment]
We decided not to use npm_assets since the repository looked dead. Since we can't use rails-assets, we had to copy T3 into the site manually.
