### ISSUE TITLE
pass data from module to behavior

### ISSUE THREAD

**Issue by signals4change** [box/t3js#62]
Hi there

I want to pass some data from module to behavior. can I do it?
I handle onclick in module and behavior. I know that  module handler called first, and then behavior handler. In normal bubbling when return some value from inner handler  I can get it in outer handler as event.result 
but this is not a bubbling then what is the solution?

**Comment by priyajeet** [comment]
Someone may correct me, but I don't believe there is a way of passing data actively from modules to behaviors or vice versa. You can however share static data between a module and its behaviors by having a script of type text/x-config with stringify-ed json. Then such data can be access via context.getConfig() within the module and its behaviors. However of course this is static read only.

Example: http://jsfiddle.net/Darth/d54efn98/.

Alternatively you can have an intermediate service that can be used as a data transport. The example above also has that.

**Comment by nzakas** [comment]
This is explicitly not allowed to preserve loose coupling. The workarounds are as Priyajeet mentioned.

**Comment by signals4change** [comment]
Thanks for solution. but I don't think passing data as event.data or event.result is coupling.

**Comment by nzakas** [comment]
Configs must be set at the time of module creation. They aren't to be used to store arbitrary data, so there's no need for `setConfig`
