### ISSUE TITLE
Behavior event handlers shouldn't be called if event.stopImmediatePropagation() is called

### ISSUE THREAD

**Issue by signals4change** [box/t3js#63]
Hi there

I think when event handler in module return false, event handlers in behaviors must not be called.
propose change in *bindEventType* function for simulate bubbling between module and behaviors: 

<pre>
function bindEventType(element, type, handlers) {
		function eventHandler(event) {
			var targetElement = getNearestTypeElement(event.target),
				elementType = targetElement ? targetElement.getAttribute('data-type') : '',
                result
                ;

			for (var i = 0; i < handlers.length; i++) {
                //handlers[i](event, targetElement, elementType);                
				result = handlers[i](event, targetElement, elementType);
                if(result===false) return false;                
			}

			return result;
		}

		// @NOTE(nzakas): Using jQuery for event normalization
		$(element).on(type, eventHandler);

		return eventHandler;
	}
<pre>

**Comment by nzakas** [comment]
The way we specified to do this is to call `event.stopImmediatePropagation()`. However, I see that isn't working currently. We should fix it so it does.

**Comment by j3tan** [comment]
Do we guarantee that when (module => behavior A => behavior B) that event.stopImmediatePropagation() called in module stops Behavior A & B and a event.stopImmediatePropagation() in Behavior A only stops only B?

Also, is there a way to detect if an event is stopped without using jQuery? I don't see anything in the Event spec.

**Comment by nzakas** [comment]
If we start by implementing #47, we could use that internally to setup event handlers. Then, the browser would handle `event.stopImmediatePropagation()` on its own (assuming we had one `DOMEventDelegate` for each module and behavior, and they were created in order on the same element). So, we wouldn't need to detect anything, we would get it for free.
