### ISSUE TITLE
Possibly make some application methods chainable

### ISSUE THREAD

**Issue by jonathanamartin** [box/t3js#65]
Hey very nice app architecture framework.  Where I work we have a need to use progressive enhancement quite a bit and I found most other app architecture frameworks didn't make it easy to serve HTML from the server.  We just needed something simple to help organize our JavaScript.  This looks to fit the bill.

On to my question.  We'd like to lazy-load not only the module HTML but also the JavaScript file associated with it.

From the few tests I've done it looks to be possible, we'd just have to make sure each T3 component starts itself rather than using the Box.Application.init method (at least I think that'll work.. if there's a cleaner way... I'm all ears).

With that said, would it be possible to make Box.Application.addModule, addService, etc. return an instance of the application instead of `undefined`.  This way I could do something like the following:

```javascript
Box.Application.addModule('some-module', function(context) {

    'use strict';

    return {

        init: function() {
		
	},

	destroy: function() {
		
        }
    };

}).start(document.getElementById('some-module'));
```
This is really more of a stylistic preference but would be nice to have.

**Comment by nzakas** [comment]
Here's some info on dynamically loading modules:
http://t3js.org/docs/guides/dynamic-loading

I don't see any reason we can't add chaining. @j3tan thoughts?

**Comment by jonathanamartin** [comment]
Hey thanks!
