### ISSUE TITLE
So what if I want to subscribe an even inside React component

### ISSUE THREAD

**Issue by rui-infotrack** [box/t3js#66]
Consider code below:
```javascript
var UI = React.createClass({
  getInitialState: function() {
    return 'initial text';
  },

  render: function() {
    return (<div>{this.state.text}</div>);
  }
});

Application.addModule('ui', function(context) {
  return {
    messages: ['update'],

    onmessage: function(name) {
      if (name == 'update') {
        context.ui.setState({text: 'updated'});
      }
    },
    
    init: function() {
        context.ui = React.render(<UI />, document.getElementById('root'));
    }
  };
});

Application.init();
```
As you can see that to update the React component (UI), we often `setState`, but in this case, the UI needs to expose itself to module context, so that later on in `onmessage` function, we can reference it. Is there any way that we can directly subscribe to certain messages inside the React component?

Thank you

**Comment by priyajeet** [comment]
I would try something like this

```js
Application.addService('UI', function(application) {
    return React.createClass({
        getInitialState: function() {
            return 'initial text';
        },

        render: function() {
            return (<div>{this.state.text}</div>);
        }
    });
});

Application.addModule('ui-wrapper', function(context) {
    var UI;
    return {
        messages: ['update'],

        onmessage: function(name) {
            if (name == 'update') {
                UI.setState({text: 'updated'});
            }
        },

        init: function() {
            UI = context.getService('UI');
            React.render(<UI />, context.getElement());
        }
    };
});
```

**Comment by rui-infotrack** [comment]
@priyajeet Thank you. I'll try this. It seems in this case, the module must hold a reference to UI and explicitly update it when message received. What I initially wanted is that the UI itself is aware of the message and update itself; but it can be argued that UI should be dumb enough so that it should be totally controlled by module.

**Comment by priyajeet** [comment]
Just thinking out aloud here, I think for that you will have to have some loose coupling outside the T3 system, like having some event bus where the UI can subscribe to events and the module publishes events. You can also achieve this also by using the document.body as the event bus via publishing CustomEvent() and using addEventListener.

**Comment by priyajeet** [comment]
Another potential recommendation


```js
Application.addService('UI', function(application) {
    return React.createClass({
        render: function() {
            return (<div>{this.props.text}</div>);
        }
    });
});

Application.addModule('ui-wrapper', function(context) {
    var UI;

    function render(text) {
        React.render(<UI text={text}/>, context.getElement());
    }

    return {
        messages: ['update'],

        onmessage: function(name) {
            if (name == 'update') {
                render('updated');
            }
        },

        init: function() {
            UI = context.getService('UI');
            render('initial text');
        }
    };
});
```

**Comment by nzakas** [comment]
You can use `Box.Application.on("message ")`. See #43

**Comment by priyajeet** [comment]
Oh totally forgot about that...

**Comment by rui-infotrack** [comment]
Thank you both @priyajeet and @nzakas. I think I'll use `Application.on('message')`.
