### ISSUE TITLE
Module Name in Creater Context

### ISSUE THREAD

**Issue by jonathanamartin** [box/t3js#67]
I'd like to re-use the module name for namespacing things like events and CSS classes.  I could replicate the name in a private variable like this:

```javascript
Box.Application.addModule('some-module', function(context) {
	
	'use strict';

	var MODULE_NAME = 'some-module';
	
	function broadcast ( name, data ) {
		context.broadcast( MODULE_NAME + ':' + name, data );
	};
	
	return {
					
		onclick: function(event, element, elementType) {
			
			// TODO: Handle specific events...
			broadcast('show', 'some data');
		},
						
		init: function() {
			// ...
		},
						
		destroy: function() {
			// ...
		}
					
	};
			
});
```

However, it'd be nice not to have to replicate the name since it's already defined.  Would it be possible to add the module's name to the `this` context inside of the creator function?  Then I could do something like:

```javascript
Box.Application.addModule('some-module', function(context) {
	
	'use strict';

	var MODULE_NAME = this.name;
	
	function broadcast ( name, data ) {
		context.broadcast( MODULE_NAME + ':' + name, data );
	};
	
	return {
					
		onclick: function(event, element, elementType) {
			
			// TODO: Handle specific events...
			broadcast('show', 'some data');
		},
						
		init: function() {
			// ...
		},
						
		destroy: function() {
			// ...
		}
					
	};
			
});
```
Or if there's already another way to get the name, I'd love to hear about it.

**Comment by nzakas** [comment]
There's no `this` in the creator function, so that's not an option.

Is there a reason you don't put the module name into a variable and then use that both in `addModule` and inside the creator function?

**Comment by jonathanamartin** [comment]
Ah I see.  Not a problem, I can use a variable.

**Comment by marco-rozz** [comment]
The module name can be retrieved in this manner:
```javascript  
var MODULE_NAME = context.element.getAttribute("data-module");
```

**Comment by jonathanamartin** [comment]
Hey thanks..  That looks pretty straight forward.
