### ISSUE TITLE
Third param to addService?

### ISSUE THREAD

**Issue by jbellsey** [box/t3js#68]
Is there any documentation on the third param to addService()? It's being used in the [ToDo router](https://github.com/box/t3js/blob/gh-pages/examples/todo/live/js/services/router.js). It looks like it lets you attach methods directly to the `application` object, with room to expand this behavior in the future.

Is this API public, functional, and intentional? And are these exports available to other services, or only as a shorthand for the service doing the exporting? Etc :)

**Comment by nzakas** [comment]
Ah yes, we use it so infrequently that we aren't sure about keeping it. The intent was to allow services to place methods on `context`  via `Application`, so you wouldn't always need to type `getService` for common functionality. 

I'd advise against using it, we should update the example to not use it as well.

**Comment by jbellsey** [comment]
Thanks, makes sense, and I agree with the direction. File under "destructive enhancement" (if that's not a term, it should be), and close this issue at your convenience.

**Comment by nzakas** [comment]
Oops, wrong button. I'll leave this open to make sure we update the example.
