### ISSUE TITLE
"Learn More" link gets hidden beneath Download button at some viewport widths

### ISSUE THREAD

**Issue by domchristie** [box/t3js#70]
![screen shot 2015-06-09 at 14 56 28](https://cloud.githubusercontent.com/assets/111734/8059443/f009e302-0eb7-11e5-92c2-9a76b090ed36.png)

I believe this might be best fixed my moving the Learn More link inside the hero, and removing the relative positioning.

**Comment by nzakas** [comment]
At what viewport size do you see this?

**Comment by domchristie** [comment]
At widths between 642-832px

**Comment by domchristie** [comment]
I’d be happy to work on this if you’d like

**Comment by nzakas** [comment]
Absolutely!
