### ISSUE TITLE
1.3.0 doesn't include support for CommonJS, etc...

### ISSUE THREAD

**Issue by FabienMotte** [box/t3js#72]
It was included in the framework on 1.2.0 version, but I can't use it on 1.3.0 version.
So I'm not able to use T3 with Browserify (for example).

Maybe a problem with the release script ?
It should include this file : [lib/wrap-end.partial](/box/t3js/blob/master/lib/wrap-end.partial)
But it doesn't seem to include it...

Thanks !

**Comment by nzakas** [comment]
You're right, it looks like t3.js is missing the CommonJS wrapper for some reason. The build script must not be working correctly. @j3tan ?

**Comment by j3tan** [comment]
The DOM abstraction commit removed commonJS/AMD support, I'll add it back in!

**Comment by j3tan** [comment]
@nzakas Re-added the wrappers
