### ISSUE TITLE
Download links on t3js.org 404

### ISSUE THREAD

**Issue by domchristie** [box/t3js#74]
On t3js.org, both download links 404, e.g.:

http://cdn.rawgit.com/box/t3js/vv1.4.0/dist/t3.js

Looks like there is an additional “v” in the URL.

http://cdn.rawgit.com/box/t3js/v1.4.0/dist/t3.js works fine

**Comment by j3tan** [comment]
Thanks for the report, looks like the new automated push process to gh-pages has the 'v' in the version

**Comment by domchristie** [comment]
Great, thanks!
