### ISSUE TITLE
Change entry point in package.json

### ISSUE THREAD

**Issue by FabienMotte** [box/t3js#76]
The actual `main` entry point in [`package.json`](https://github.com/box/t3js/blob/master/package.json) file is :
```json
"main": "dist/t3.js"
```
And this version of T3 still depends on jQuery.

Now that there is a [native version](https://github.com/box/t3js/blob/master/dist/t3-native.js) of the framework (without jQuery dependency), it would be great to have it included as the new entry point in [`package.json`](https://github.com/box/t3js/blob/master/package.json) file :
```json
"main": "dist/t3-native.js"
```

It would allow us to `require('t3js')` (with Browserify for example) without the need to require also jQuery and pollute the global scope to make it work with T3.

Any thoughts about it ?

Thanks !

**Comment by j3tan** [comment]
Good idea, people using browserify probably have access to es5 stuff or babel. Thoughts @nzakas ?

**Comment by nzakas** [comment]
This would be a breaking change as there are some things jQuery allows you to do (custom selectors, `focusin`, etc.) that native does not. Some discussion around that point: https://github.com/box/t3js/issues/22

So the real question is if this is important enough to do now and go to 2.0.0, or if we can wait?

**Comment by nzakas** [comment]
Just an update: for 2.0.0, we are going to switch the default version of T3 to be the native one, both in `package.json` and the hosted files. This will be a breaking change, so we'll hold off until to get some non-breaking changes in first.
