### ISSUE TITLE
Expand captureObjectErrors to wrap behaviors and services in addition to modules

### ISSUE THREAD

**Issue by jdivock** [box/t3js#80]
This came up while looking for a way to have captureObjectErrors also provide metadata as to whether an errors spawned for a behavior, service, or module. We learned that only modules were being wrapped so errors from services and behaviors aren't falling into this logic path where we can wrap them properly. 

Discussion of providing this came about from https://github.com/box/t3js/pull/78

**Comment by nzakas** [comment]
Closed by #78
