### ISSUE TITLE
How about TypeScript Definitions?

### ISSUE THREAD

**Issue by SergeySidorchuk** [box/t3js#81]
It will be great to use T3 together with TypeScript language. Have you any plans to write TypeScript definitions for T3?

**Comment by nzakas** [comment]
We don't have any experience with TypeScript, so this wasn't on our to-do list. If you'd like to contribute the definitions, we will gladly accept them.

**Comment by nzakas** [comment]
As we don't have the expertise to do this, closing. If anyone would like to volunteer to contribute TypeScript defintions, please leave a comment.

**Comment by albertosantini** [comment]
See also https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7248.

The issue above contains a reference to the following gist:
https://gist.github.com/webbiesdk/fa0a5ce63b10bd01f9f9
