### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by CrowdHailer** [box/t3js#83]
Is there a way to organise submodules? This is probably not an issue but I could not see a place to just ask questions

**Comment by nzakas** [comment]
We explicitly don't support relationships between modules in order to enforce loose coupling. So, there's no way to create parent-child relationships (submodules).

**Comment by CrowdHailer** [comment]
Thanks for the reply and I think I understand that rational.
To make further comment I have a project that consists of a main panel and a side menu with 4 separate panel. Each side panel is complex, certainly worthy of being a module. If I make each panel a module then I wonder where to put the code that is responsible for switching between Panels

Any Illumination on this would be very helpful.

**Comment by nzakas** [comment]
It's very difficult to talk in the abstract about this, but it seems like you should have a sidepanel service that the main module calls. Then the sidepanel service can figure out which module to load.

**Comment by CrowdHailer** [comment]
It is indeed. Well thanks for the comments anyways. I am still looking out for any larger examples if any exist. either with t3 or just build using ideas like t3's
