### ISSUE TITLE
Context Documentation

### ISSUE THREAD

**Issue by CrowdHailer** [box/t3js#84]
For the context object there is a broadcast method. http://t3js.org/docs/api/context/#broadcast
Should there also be a listen method? I am watching 03 Creating 'A Scalable JavaScript Application Architecture Nicholas Zakas' and looking for the equivalent to `sandbox.listen`

**Comment by CrowdHailer** [comment]
apologies I have now found how this works. in the module documentation and not the context/application documentation where i was looking

**Comment by nzakas** [comment]
Yup, see http://t3js.org/docs/guides/modules for info on how to listen to messages.
