### ISSUE TITLE
Question on dynamic module

### ISSUE THREAD

**Issue by trunghung** [box/t3js#92]
I apologize for opening an issue when my question isn't an actual issue.  I don't know if there is a forum where I can ask questions about t3js.  I am new to t3js so please bare with me.  Please let me know if it's possible to do what I am asking currently or I need to make code for it. I am also open to suggestions on alternative approaches that I can use to solve these questions.  thanks

1. A lot of our app UI modules are loaded dynamically, and I would like the modules to be as self contained as possible.  Currently the only way I see a module can be loaded is insert some markup into the dom and call Application.start on it.  I would like to be able to start a module without the markup in the dom.  I want my module to be able to inject itself into the dom element I am passing in, and clean up itself. 
2. Is it possible to configure the context?  I am plugging in other modules developed by other teams that doesn't use t3js. They be looking for contextObj.viewport instead of contextObj.element or contextObj.getElement().  I would like to be able to augment some additional method to the context so that I can customize it for the various modules I am using.  
thanks

**Comment by nzakas** [comment]
1. Modules are designed to be in the DOM, there's no way to start a module that isn't in the DOM already. 
2. No, context is specifically designed to not be configured. It's job is to provide a consistent interface that is the same for every module. If you need to expose other functionality, then you would do so by creating a service and adding the extra functionality there.
