### ISSUE TITLE
Comments in text/x-config causing error

### ISSUE THREAD

**Issue by pytkin** [box/t3js#98]
Hello, guys. 
If I'm using comments in module config it's causing error:  `Uncaught SyntaxError: Unexpected token /` (in debug mode).

Example: 
```
<script type="text/x-config">
{
  "currentDate": "19.09.2015", /* */ or //
  "minDateRange": 1,
  "maxDateRange": 10
}
</script>
```

Maybe you'll should use JSON.stringify() before calling JSON.parse() here: https://github.com/box/t3js/blob/master/dist/t3.js#L1097 ?

**Comment by nzakas** [comment]
JSON doesn't allow comments, so what you have is invalid syntax.
